version: "2"
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=http://localhost:6875
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_USER=bookstack  #usuario MySQL
      - DB_PASS=password_db #password de base de datos
      - DB_DATABASE=bookstackapp  # Nombre Base de Datos
    volumes:
      - ./bookstack_app_data:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=password_mysql #password de root de mysql
      - TZ=America/Lima  #Zona Horaria
      - MYSQL_DATABASE=bookstackapp   # Nombre Base de Datos
      - MYSQL_USER=bookstack #Usuario MySQL
      - MYSQL_PASSWORD=password_db  #password de base de datos
    volumes:
      - ./bookstack_db_data:/config
    restart: unless-stopped
